config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :pins do
    resources :comments
    member do
    put "like", to: "pins#upvote"
    put "unlike", to: "pins#unvote"

    end
  end

  get "my", to: "pins#show_my"
  delete "del", to: "pins#delete_my"

  root "pins#index"

devise_scope :user do
  delete 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session_omni
end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :pin
  belongs_to :user
end

app/models/pin.rb
class Pin < ActiveRecord::Base
  acts_as_votable
  belongs_to :user
  has_many :comments
  has_attached_file :image, styles: { medium: "300x300>" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
  validates :title, :description, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  acts_as_voter
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :pins
  has_many :comments
  devise :omniauthable, :omniauth_providers => [:facebook]

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
    end
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :find_pin
  before_action :find_comment, only: [:edit, :update, :destroy]
  before_action :authenticate_user!



  def create
    @comment = @pin.comments.create(comment_params)
    @comment.user_id = current_user.id
    @comment.save

    if @comment.save
      redirect_to pin_path(@pin)
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @comment.update(comment_params)
      redirect_to pin_path(@pin)
    else
      render 'edit'
    end
  end

  def destroy
    @comment.destroy
    redirect_to pin_path(@pin)
  end

  private

  def comment_params
    params.require(:comment).permit(:content)
  end

  def find_pin
    @pin = Pin.find(params[:pin_id])
  end

  def find_comment
    @comment = @pin.comments.find(params[:id])
  end

end

app/controllers/pins_controller.rb
class PinsController < ApplicationController

  before_action :find_pin, only: [:show, :edit, :update, :destroy, :upvote, :unvote]
  before_action :authenticate_user!, except: [:index, :show]
  rescue_from ActiveRecord::RecordNotFound, with: :pin_not_found

  before_action :find_my, only: [:show_my, :delete_my]


  def index
    @pins = Pin.all.order("created_at DESC")
  end


  respond_to do |format|
      if @test.save
        format.html { redirect_to @test, notice: 'Test was successfully created.' }
        format.json { render :show, status: :created, location: @test }
      else
        format.html { render :new }
        format.json { render json: @test.errors, status: :unprocessable_entity }
      end
    end

  def show

  end

  def new
    @pin = current_user.pins.build
  end

  def create
    @pin = current_user.pins.build(pin_params)

    if @pin.save
      redirect_to @pin, notice: "Successfully created new Pin"
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @pin.update(pin_params)
      redirect_to @pin, notice: "Pin wass successfully updated"
    else
      render 'edit'
    end
  end

  def destroy
    @pin.destroy
    redirect_to root_path
  end

  def upvote
    @pin.liked_by current_user
    respond_to do |format|
    format.html { redirect_to :back }
    format.js
  end
  end

  def unvote
    @pin.unliked_by current_user
    respond_to do |format|
    format.html { redirect_to :back }
    format.js
  end
  end

  def show_my
  end

  def delete_my
    @pins.delete_all
    redirect_to root_path

  end

  private
  def pin_params
    params.require(:pin).permit(:title, :description, :image)
  end

  def find_my
    @pins = Pin.where(["user_id = ?", current_user.id])
  end

  def find_pin
    @pin = Pin.find(params[:id])
  end

  def pin_not_found
    logger.error "Attempt to access a non-existent pin #{params[:id]}"
    redirect_to root_path, notice: 'Pin not found'
  end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/comments/_comment.html.haml
.comment
  %p.comment-content= comment.content
  %p.comment-posted-by
    Posted by #{comment.user.email} #{time_ago_in_words(comment.created_at)} ago
  .links
    - if user_signed_in?
      - if comment.user_id == current_user.id || @pin.user_id == current_user.id
        = link_to "Edit", edit_pin_comment_path(comment.pin, comment)
        = link_to "Delete", pin_comment_path(comment.pin, comment), method: :delete, data: { confirm: "Are you sure?" }

app/views/comments/_form.html.haml
= simple_form_for([@pin, @pin.comments.build]) do |f|
  = f.input :content, label: "Comment"
  = f.button :submit, :class => 'btn-custom'

app/views/comments/edit.html.haml
%h1 Edit Comment
= simple_form_for([@pin, @comment]) do |f|
  = f.input :content, label: "Comment"
  = f.button :submit

app/views/layouts/application.html.haml
!!! 5
%html
%head
  %title Pin Board
  = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
  = javascript_include_tag 'application', 'data-turbolinks-track' => true
  = csrf_meta_tags
%body
  - if notice
    #notice-wrapper
      %p.notice= notice
  - elsif alert
    #notice-wrapper
      %p.alert= alert
  %nav.navbar.navbar-default
    .container
      .navbar-brand= link_to "Pin Board", root_path

      - if user_signed_in?
        %ul.nav.navbar-nav.navbar-right
          %li= link_to "Delete All My Pins", del_path, method: :delete, data: { confirm: "Are you sure?" }, class: "nav-button"
          %li= link_to "My Pins", my_path, class: "nav-button"
          %li= link_to "New Pin", new_pin_path, class: "nav-button"
          %li= link_to "Account", edit_user_registration_path, class: "nav-button"
          %li= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "nav-button"
      - else
        %ul.nav.navbar-nav.navbar-right
          %li= link_to "Sign up", new_user_registration_path, class: "nav-button"
          %li= link_to "Sign In", new_user_session_path, class: "nav-button"
  .container
    = yield

:javascript
  $(document).ready(function(){
    setTimeout(function(){
      $('#notice-wrapper').fadeOut("slow", function() {
        $(this).remove();
      })
    }, 3500);
  });

app/views/pins/_form.html.haml
= simple_form_for @pin, html: { multipart: true } do |f|
  -if @pin.errors.any?
    #errors
      %h2
      =pluralize(@pin.errors.count, "error")
      prevented this Pin from saving
      %ul
        - @pin.errors.full_messages.each do |msg|
          %li= msg

  .form-group
    = f.input :image, input_html: { class: 'form-control' }

  .form-group
    = f.input :title, input_html: { class: 'form-control' }
  .form-group
    = f.input :description, input_html: { class: 'form-comtrol' }

  = f.button :submit, class: "btn btn-primary"

app/views/pins/_show_buttons.html.haml
- if user_signed_in?
  .btn-group.pull-right
    - if current_user.voted_as_when_voted_for @pin
      = link_to unlike_pin_path(@pin), method: :put, class: "btn btn-primary", remote: true do
        %span.glyphicon.glyphicon-star-empty
          = @pin.get_upvotes.size
    - else
      = link_to like_pin_path(@pin), method: :put, class: "btn btn-default", remote: true do
        %span.glyphicon.glyphicon-star-empty
          = @pin.get_upvotes.size
    - if @pin.user_id == current_user.id
      = link_to "Edit", edit_pin_path, class: "btn btn-default"
      = link_to "Delete", pin_path, method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-default"

app/views/pins/edit.html.haml
#edit_page.col-md-8.col-md-offset-2
  .row
    .panel.panel-default
      .panel-heading
        %h1 Edit Your Pin
      .panel-body
        .current_image
          %strong.center Current Image
          = image_tag @pin.image.url(:medium)
        = render 'form'

app/views/pins/index.html.haml
#pins.transitions-enabled
  - @pins.each do |pin|
    .box.panel.panel-default
      = link_to (image_tag pin.image.url), pin
      .panel-body
        %h2= link_to pin.title, pin
        %p.user
        Submitted by
        = pin.user.email
%a#toTop{:href => "#"}

app/views/pins/new.html.haml
.col-md-6.col-md-offset-3
  .row
    .panel.panel-default
      .panel-heading
        %h1 New Form
      .panel-body
        = render 'form'

app/views/pins/show.html.haml
#pin_show.row
  .col-md-8.col-md-offset-2
    .panel.panel-default
      .panel-heading.pin_image
        = image_tag @pin.image.url(:medium)
      .panel-body
        %h1= @pin.title
        %p.description= @pin.description
        %p
        Submitted by
        = @pin.user.email
        .row
          .col-md-6

          .col-md-6
            = render 'show_buttons'
      .panel-footer
        %h3 Comments
        = render @pin.comments
        %h3.reply-to-pin Reply to Pin
        - if user_signed_in?
          = render 'comments/form'
        - else
          = link_to "Log In", new_user_session_path
          to add a comment

app/views/pins/show_my.html.haml
- unless @pins.any?
  %h2 You have no pins but u can create your
  %h2= link_to "first one.", new_pin_path
- else
  #pins.transitions-enabled
    - @pins.each do |pin|
      .box.panel.panel-default
        = link_to (image_tag pin.image.url), pin
        .panel-body
          %h2= link_to pin.title, pin
          %p.user
          Submitted by
          = pin.user.email

app/views/pins/unvote.js.erb
$('.btn-group.pull-right').html('<%=j render partial: 'show_buttons' %>');

app/views/pins/upvote.js.erb
$('.btn-group.pull-right').html('<%=j render partial: 'show_buttons' %>');